# Generated by Django 3.2.4 on 2021-06-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_duration', models.IntegerField(default=60)),
                ('pause_duration', models.IntegerField(default=30)),
                ('working_days', models.ManyToManyField(to='configuration.WorkingDay')),
            ],
        ),
    ]
