# Generated by Django 3.2.4 on 2021-06-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.IntegerField()),
                ('end_at', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('period_duration', models.IntegerField(default=60)),
                ('pause_duration', models.IntegerField(default=30)),
                ('begin_at', models.IntegerField(default=8)),
                ('end_at', models.IntegerField(default=18)),
                ('Monday', models.BooleanField(default=True)),
                ('Tuesday', models.BooleanField(default=True)),
                ('Wednesday', models.BooleanField(default=True)),
                ('Thursday', models.BooleanField(default=True)),
                ('Friday', models.BooleanField(default=True)),
                ('Saturday', models.BooleanField(default=True)),
                ('Sunday', models.BooleanField(default=False)),
                ('pauses', models.ManyToManyField(to='configuration.Pause')),
            ],
        ),
    ]
