# Generated by Django 3.2.4 on 2021-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='pause_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='config',
            name='period_duration',
            field=models.IntegerField(default=1),
        ),
    ]
