# Generated by Django 3.2.4 on 2021-07-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20210706_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='pauses',
            field=models.ManyToManyField(blank=True, to='configuration.Pause'),
        ),
    ]
