# Generated by Django 3.2.4 on 2021-06-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('begin_at', models.IntegerField(default=8)),
                ('end_at', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField()),
                ('last_day', models.DateField(null=True)),
                ('is_ok', models.BooleanField(default=False)),
                ('configurations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.config')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_begin', models.IntegerField()),
                ('hour_end', models.IntegerField(null=True)),
                ('is_pause', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('was_occupied', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekschedule.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekschedule.week'),
        ),
    ]
