# Generated by Django 3.2.4 on 2021-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekschedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
