# Generated by Django 3.2.4 on 2021-07-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
        ('weekschedule', '0003_week_level_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='level_class',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teaching.class'),
        ),
    ]
