# Generated by Django 3.2.4 on 2021-07-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
        ('weekschedule', '0004_alter_week_level_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='period',
            name='occupied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teaching.course'),
        ),
    ]
